'use client'

import Navbar from '@/Components/Navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer/Footer'
import { useRouter } from 'next/navigation'
import { usePathname, useSearchParams } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const router = useRouter()
  const pathname = usePathname()
  const searchParams = useSearchParams()
  const showHeader = pathname === '/Login' ? false : true;
  console.log(pathname)
  return (
    <html lang="en">
      <body className={inter.className}>
      {showHeader && <Navbar />}
        {children}
        {showHeader &&  <Footer/>}
       
        </body>
    </html>
  )
}
