'use client'

import Navbar from '@/Components/Navbar/Navbar'
import './globals.css'
import 'aos/dist/aos.css'
import AOS from 'aos'
import { Inter } from 'next/font/google'
import Footer from '@/Components/Footer/Footer'
import { useRouter } from 'next/navigation'
import { usePathname, useSearchParams } from 'next/navigation'
import { useEffect } from 'react'
import Aos from 'aos'
import Head from 'next/head'
import { createWrapper } from 'next-redux-wrapper';
import { Provider } from 'react-redux';
import { Providers } from '@/Services/Redux/provider'
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  useEffect(()=>{
    Aos.init({
      duration: 800,
      once: false
    },[])
  })
  const router = useRouter()
  const pathname = usePathname()
  const searchParams = useSearchParams()
  const showHeader = pathname === '/Login'  ? false : true;
  const showHeaders = pathname === '/Signup'  ? false : true;
  console.log(pathname)

  return (
    <html lang="en">
      <Head>
      <link href="https://fonts.googleapis.com/css2?family=Circular+Spotify+Text:wght@300;400;500;600;700&display=swap" rel="stylesheet" />
      <title>My page title</title>
      <link rel="icon" href="/assets/Search.svg" sizes="any" />
      </Head>
      <body className={inter.className}>
        <Providers >
      {showHeader && showHeaders && <Navbar />}
        {children}
        {showHeader && showHeaders && <Footer/>}
        </Providers>
        </body>
    </html>
  )
}
